import os
import sys
import subprocess
import shutil
from pathlib import Path
from setuptools import setup, Extension
from setuptools.command.install import install
from setuptools._distutils.command.clean import clean

sdanalysis_dir = os.environ.get("SDANALYSIS_DIR")
assert sdanalysis_dir is not None, "SDANALYSIS_DIR environment variable must be defined"

dst2k_ta_include = f"-I{sdanalysis_dir}/dst2k-ta/inc"
lib_dir = f"{sdanalysis_dir}/dst2k-ta/lib"

CUR_DIR = Path(__file__).parent
SRC_DIR = CUR_DIR / "src"
SWIG_DIR = CUR_DIR / "swig"
SWIG_INTERFACE_FILE = SWIG_DIR / "dstreader_core.i"
SWIG_GENERATED_PY_MODULE = "dstreader_core.py"


class InstallWithSwig(install):
    def run(self):
        cmdargs = ["swig", "-python", dst2k_ta_include, str(SWIG_INTERFACE_FILE)]
        print(" ".join(cmdargs))
        res = subprocess.run(cmdargs, capture_output=True)
        if res.returncode != 0:
            print(res.stdout.decode("utf-8"))
            print(res.stderr.decode("utf-8"))
            sys.exit(1)
        shutil.move(SWIG_DIR / SWIG_GENERATED_PY_MODULE, SRC_DIR / SWIG_GENERATED_PY_MODULE)
        install.run(self)


class CleanWithSwig(clean):
    def run(self):
        for file in SWIG_DIR.iterdir():
            if file != SWIG_INTERFACE_FILE:
                if file.is_file():
                    file.unlink()
                else:
                    shutil.rmtree(file)
        (SRC_DIR / SWIG_GENERATED_PY_MODULE).unlink(missing_ok=True)
        clean.run(self)


core_ext = Extension(
    "dstreader._dstreader_core",
    sources=[f'{SWIG_DIR}/dstreader_core_wrap.c'],  # generated by swig
    swig_opts=[dst2k_ta_include],
    library_dirs=[lib_dir],
    libraries=['dst2k', 'm', 'c', 'z', 'bz2'],
    extra_compile_args=[dst2k_ta_include],
)

setup(
    name='dstreader',
    version="0.0.1",
    author='Igor Vaiman',
    author_email='gosha.vaiman@gmail.com',
    description='TA/HiRes DST file format reader, SWIG-generated wrapper around dst2k-ta library',
    packages=['dstreader'],
    package_dir={'dstreader': 'src'},
    ext_modules=[core_ext],
    cmdclass={
        'install': InstallWithSwig,
        'clean': CleanWithSwig,
    },
)
