#!/bin/bash

# this tiny script performs post-installation configuration of tasdmc:
# it prompts user for storage directory and creates an activation script with this value
# TASDMC_RUNS_DIR and TASDMC_DATA_DIR are defined to be located inside of it

if [ -z "${CONDA_PREFIX}" ]; then
    echo "You must be inside conda environment to run tasdmc-init! Aborting"
    exit 1;
fi

if [ -z "${TASDMC_STORAGE_DIR}" ]; then
    echo "
Welcome to tasdmc!

Please specify the storage directory, in which all tasdmc stuff will be placed.
Note that this directory will occupy a significant amount of disk space (up to hundreds of Gb) if you plan on running simulations."
    read -p '> ' TASDMC_STORAGE_DIR
else
    echo "TASDMC_STORAGE_DIR environment variable found"
fi

TASDMC_STORAGE_DIR=$(readlink -f $TASDMC_STORAGE_DIR)

if [ ! -d $TASDMC_STORAGE_DIR ]; then
    echo "Specified TASDMC_STORAGE_DIR=$TASDMC_STORAGE_DIR do not exist, aborting"
    exit 1;
fi

TASDMC_DATA_DIR=$TASDMC_STORAGE_DIR/data
TASDMC_RUNS_DIR=$TASDMC_STORAGE_DIR/runs

echo "All of your runs will be placed in
${TASDMC_RUNS_DIR}

All data files must be present in
${TASDMC_DATA_DIR}
"

mkdir -p $TASDMC_DATA_DIR
mkdir -p $TASDMC_RUNS_DIR

ACTIVATION_SCRIPTS_DIR=$CONDA_PREFIX/etc/conda/activate.d
mkdir -p $ACTIVATION_SCRIPTS_DIR
ACTIVATION_SCRIPT=$ACTIVATION_SCRIPTS_DIR/tasdmc-activate-configured.sh
touch $ACTIVATION_SCRIPT
echo "export TASDMC_DATA_DIR=$TASDMC_STORAGE_DIR/data" >> $ACTIVATION_SCRIPT
echo "export TASDMC_RUNS_DIR=$TASDMC_STORAGE_DIR/runs" >> $ACTIVATION_SCRIPT

echo "Reactivate environment for changes to take effect, e.g."
echo "> conda deactivate"
echo "> conda activate ${CONDA_DEFAULT_ENV}"

echo "
Installing tasdmc dependencies with pip
WARNING: if you use this conda environment for anything other than tasdmc, this may lead to conflicts
"
# pip commands are added here in conda package build time from requirements.txt
