# this is a main configuration file with most physical and technical parameters of the simulation
# see README for detailed comments

name: your-run-name
description:
  Optional detailed description of run's purpose and other info.

pipeline:
  produce_tawiki_dumps: True
  legacy_corsika2geant: False
  batch_size_multiplier: 2

input_files:
  particle: proton
  log10E_min: 17.5
  log10E_max: 20.5
  event_number_multiplier: 1.0

corsika:
  path: full/path/to/corsika/executable
  low_E_hadronic_interactions_model: GHEISHA
  high_E_hadronic_interactions_model: QGSJETII
  default_executable_name: True

dethinning:
  n_parallel: 6

throwing:
  n_events_at_min_energy: 1e6
  dnde_exponent: 2
  sdmc_spctr_executable_name: null
  sdmc_spctr_n_try: 10
  smear_events_in_bin: True
  calibration_dir: sdcalib_13_yrs_from_2008_to_2021

spectral_sampling:
  target: HiRes
  aux_log10E_min:
    - 18.95
    - 19.45

resources:
  max_processes: 2
  monitor_interval: 60

debug:
  input_hashes: False
  file_checks: False
  external_routine_commands: False
  pipelines_mask: []
  force_rerun_steps: []
