package:
  name: tasdmc
  version: "0.1.0"

source:
  path: ../

requirements:
  build:
    - python 3.9
    - pip
    - root
    - bz2file
    - setuptools
  run:
    - python 3.9

about:
  home: https://github.com/nj-vs-vh/tasdmc
  summary: Telescope Array Surface Detector Monte Carlo simulation pipeline
