{% set data = load_setup_py_data() %}

package:
  name: tasdmc
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python 3.9
    - pip
    - root
    - bz2file
    - bzip2
    - setuptools
    - libgcc-ng
    - libstdcxx-ng
  run:
    - python 3.9

about:
  home: https://github.com/nj-vs-vh/tasdmc
  summary: Telescope Array Surface Detector Monte Carlo simulation pipeline
