name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      # - name: compiling check_gea_dat_file.run
      #   run:
      #     . tests/test_env.sh &&
      #     cd src/c_routines &&
      #     make bin/check_gea_dat_file.run &&
      #     cp bin/check_gea_dat_file.run / &&
      #     cd ../..
      
      - name: installing python requirements
        run: pip install -r requirements.txt
      
      - name: installing tasdmc package
        run: python setup.py install
      
      - name: running tests
        run:
          . tests/test_env.sh && 
          pytest tests -vv
